;integer and real package (same as scheme number, only tagged)
(define (install-integer-package)
  (define (tag x) (attach-tag 'integer x))
  (put 'add '(integer integer)
       (lambda (x y) (tag (+ x y))))
  (put 'sub '(integer integer)
       (lambda (x y) (tag (- x y))))
  (put 'mul '(integer integer)
       (lambda (x y) (tag (* x y))))
  (put 'div '(integer integer)
       (lambda (x y) (make-rational x y)))
  (put 'minus '(integer) (lambda (x) (tag (- x))))
  (put 'my-equ? '(integer integer) =)
  (put '=zero? '(integer)
       (lambda (x) (= x 0)))
  (put 'raise-type 'integer
       (lambda (x) (make-rational x 1)))
  (put 'make 'integer identity)
  '(done integer))

(define (make-integer x)
  ((get 'make 'integer) x))
