
(define (install-rectangular-package)
  (define (real-part z) (car z))
  (define (imag-part z) (cdr z))
  (define (make-from-real-imag x y) (cons x y))
  (define (magnitude z)
    (sqrt (+ (square (real-part z))
             (square (imag-part z)))))
  (define (angle z)
    (atan (imag-part z) (real-part z)))
  (define (make-from-mag-ang r a)
    (cons (* r (cos a)) (* r (sin a))))

  (define this-type-tag 'rectangular)
  (define (tag x) (attach-tag this-type-tag x))
  (put 'real-part (list this-type-tag) real-part)
  (put 'imag-part (list this-type-tag) imag-part)
  (put 'magnitude (list this-type-tag) magnitude)
  (put 'angle (list this-type-tag) angle)
  (put 'make-from-real-imag this-type-tag
       (lambda (x y) (tag (make-from-real-imag x y))))
  (put 'make-from-mag-ang this-type-tag
       (lambda (r a) (tag (make-from-mag-ang r a))))
  '(done rectangular))

(define (install-polar-package)
  (define (magnitude z) (car z))
  (define (angle z) (cdr z))
  (define (make-from-mag-ang r a) (cons r a))
  (define (real-part z)
    (* (magnitude z) (cos (angle z))))
  (define (imag-part z)
    (* (magnitude z) (sin (angle z))))
  (define (make-from-real-imag x y)
    (cons (sqrt (+ (square x) (square y)))
          (atan (/ y x))))

  (define this-type-tag 'polar)
  (define (tag x) (attach-tag this-type-tag x))
  (put 'real-part (list this-type-tag) real-part)
  (put 'imag-part (list this-type-tag) imag-part)
  (put 'magnitude (list this-type-tag) magnitude)
  (put 'angle (list this-type-tag) angle)
  (put 'make-from-real-imag this-type-tag
       (lambda (x y) (tag (make-from-real-imag x y))))
  (put 'make-from-mag-ang this-type-tag
       (lambda (r a) (tag (make-from-mag-ang r a))))
  '(done polar))

(define (real-part z) (apply-generic 'real-part z))
(define (imag-part z) (apply-generic 'imag-part z))
(define (magnitude z) (apply-generic 'magnitude z))
(define (angle z) (apply-generic 'angle z))

(define (install-complex-package)
  (define (make-from-real-imag x y)
    ((get 'make-from-real-imag 'rectangular) x y))
  (define (make-from-mag-ang r a)
    ((get 'make-from-mag-ang 'polar) r a))
  (define (add-complex z1 z2)
    (make-from-real-imag (+ (real-part z1) (real-part z2))
                         (+ (imag-part z1) (imag-part z2))))
  (define (sub-complex z1 z2)
    (make-from-real-imag (- (real-part z1) (real-part z2))
                         (- (imag-part z1) (imag-part z2))))
  (define (mul-complex z1 z2)
    (make-from-mag-ang (* (magnitude z1) (magnitude z2))
                       (+ (angle z1) (angle z2))))
  (define (div-complex z1 z2)
    (make-from-mag-ang (/ (magnitude z1) (magnitude z2))
                       (- (angle z1) (angle z2))))
  (define (my-equ? z1 z2)
    (and (= (real-part z1) (real-part z2))
         (= (imag-part z1) (imag-part z2))))
  (define (=zero? z)
    (and (= (real-part z) 0) (= (imag-part z) 0)))

  (define (tag z) (attach-tag 'complex z))
  (put 'add '(complex complex)
       (lambda (z1 z2) (add-complex z1 z2)))
  (put 'sub '(complex complex)
       (lambda (z1 z2) (sub-complex z1 z2)))
  (put 'mul '(complex complex)
       (lambda (z1 z2) (mul-complex z1 z2)))
  (put 'div '(complex complex)
       (lambda (z1 z2) (div-complex z1 z2)))
  (put 'my-equ? '(complex complex) my-equ?)
  (put '=zero? '(complex) =zero?)
  (put 'real-part '(complex) real-part)
  (put 'imag-part '(complex) imag-part)
  (put 'magnitude '(complex) magnitude)
  (put 'angle '(complex) angle)
  (put 'make-from-real-imag 'complex
       (lambda (x y) (tag (make-from-real-imag x y))))
  (put 'make-from-mag-ang 'complex
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (install-rectangular-package)
  (install-polar-package)
  '(done complex))

(define (make-complex-from-real-imag x y)
  ((get 'make-from-real-imag 'complex) x y))
(define (make-complex-from-mag-ang r a)
  ((get 'make-from-mag-ang 'complex) r a))
